country: [geolite2_city, dbip_city, ipapi_city_v4, ipapi_city_v6, sapics_country, ipinfo_lite, iptoasn]
continent: [geolite2_city, dbip_city, ipapi_city_v4, ipapi_city_v6, ipinfo_lite, sapics_country]
asn_number: [ipinfo_lite, sapics_origin_asn, iptoasn, geolite2_asn]
asn_org: [ipinfo_lite, iptoasn, geolite2_asn]
asn_domain: [ipinfo_lite]
city: [geolite2_city, dbip_city, ipapi_city_v4, ipapi_city_v6]
location: [geolite2_city, dbip_city, ipapi_city_v4, ipapi_city_v6]
subdivisions: [geolite2_city, dbip_city, ipapi_city_v4, ipapi_city_v6]
postal: [geolite2_city, dbip_city, ipapi_city_v4, ipapi_city_v6]
traits: or
